-- Role families generated by AI for one organisation from a recruiter's description.
CREATE TABLE custom_families (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES orgs(id),
  created_by TEXT NOT NULL REFERENCES users(id),
  role_title TEXT NOT NULL,
  description TEXT NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'done', 'failed')),
  attempts INTEGER NOT NULL DEFAULT 0,
  spec_json TEXT,
  error TEXT,
  model TEXT,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX custom_families_org ON custom_families (org_id, created_at);
