/**
 * The static demo's "server": it answers every API call from pre-written data
 * kept in this browser tab. Nothing is sent anywhere and no AI runs; reviews,
 * integrity checks, interview kits and emails were written in advance.
 *
 * Role content comes from ./content, generated by `npm run demo-data`: the
 * browser never loads role families, so answer keys stay on the server.
 */
import type {
  AssessmentDetail,
  AssessmentFunnel,
  AssessmentSummary,
  AuditEvent,
  CandidateListItem,
  CandidateReport,
  DecisionEmailDraft,
  GenerationView,
  Me,
  PlanView,
  ReportStage,
  RoleFamilyPreview,
  RoleFamilySummary,
  ScoreOverride,
  TeamMember,
} from '../../../shared/api';
import type { CandidateDraft, CandidatePhaseView, CandidateSession } from '../../../shared/candidateApi';
import { templateEmail } from '../../../shared/decisionEmail';
import { choiceKey, type DemoCandidateData } from '../../../shared/demo';
import { adjustedScores } from '../../../shared/scoreMath';
import type { CandidateStageView, Currency, Decision } from '../../../shared/types';
import { ApiError } from '../api';
import candidateJson from './content/candidate.json';
import libraryJson from './content/library.json';
import fixtures from './fixtures.json';
import { DEMO_STATE_KEY, DEMO_TOKEN, demoEpoch, exitDemo } from './mode';
import { tourState } from './tour';

const LIBRARY = libraryJson as RoleFamilySummary[];
// The candidate demo: a short version of a real assessment, timers halved.
const CANDIDATE = candidateJson as DemoCandidateData;
const PREVIEWS = import.meta.glob<{ default: Record<Currency, RoleFamilyPreview> }>('./content/previews/*.json');
const SUBMIT_GRACE_MS = 60_000;

interface CandidateResponse {
  stageId: string;
  view: CandidateStageView;
  deadlineAt: number;
  draft: CandidateDraft | null;
  closed: boolean;
  choiceId: string | null;
}

interface DemoGeneration extends GenerationView {
  baseFamilyId: string;
}

interface DemoAssessment {
  summary: Omit<AssessmentSummary, 'candidateCount' | 'counts'>;
  stageIds: string[] | null;
}

interface State {
  version: 1;
  me: Me;
  team: TeamMember[];
  plan: PlanView;
  assessments: Record<string, DemoAssessment>;
  candidates: Record<string, CandidateListItem[]>;
  funnels: Record<string, AssessmentFunnel>;
  reports: Record<string, CandidateReport>;
  emails: Record<string, Partial<Record<Decision, DecisionEmailDraft>>>;
  generations: DemoGeneration[];
  candidateDemo: {
    status: 'invited' | 'in_progress' | 'submitted';
    responses: CandidateResponse[];
  };
}

type Fixtures = {
  me: Me;
  team: TeamMember[];
  assessments: AssessmentSummary[];
  details: Record<string, AssessmentDetail>;
  funnels: Record<string, AssessmentFunnel>;
  reports: Record<string, CandidateReport>;
  emails: Record<string, Partial<Record<Decision, DecisionEmailDraft>>>;
};

function freshState(): State {
  const f = structuredClone(fixtures) as unknown as Fixtures;
  const assessments: State['assessments'] = {};
  const candidates: State['candidates'] = {};
  for (const a of f.assessments) {
    const { candidateCount: _count, counts: _counts, ...summary } = a;
    assessments[a.id] = { summary, stageIds: null };
    candidates[a.id] = f.details[a.id].candidates;
  }
  return {
    version: 1,
    me: f.me,
    team: f.team,
    plan: {
      plan: 'trial',
      name: 'Free trial',
      included: 5,
      used: 2,
      period: 'trial',
      credits: null,
      locked: 0,
      upgradeRequest: null,
    },
    assessments,
    candidates,
    funnels: f.funnels,
    reports: f.reports,
    emails: f.emails,
    generations: [],
    candidateDemo: { status: 'invited', responses: [] },
  };
}

let state: State | null = null;
let loadedEpoch = -1;

function load(): State {
  if (state && loadedEpoch === demoEpoch()) return state;
  state = null;
  loadedEpoch = demoEpoch();
  try {
    const saved = sessionStorage.getItem(DEMO_STATE_KEY);
    if (saved) state = JSON.parse(saved) as State;
  } catch {
    state = null;
  }
  if (!state || state.version !== 1) state = freshState();
  return state;
}

function save() {
  try {
    sessionStorage.setItem(DEMO_STATE_KEY, JSON.stringify(state));
  } catch {
    // Storage full or blocked: changes last until the tab is reloaded.
  }
}

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
/** A pause that stands in for AI writing something; short while a guided tour is driving the page. */
const writing = (ms: number) => wait(tourState() ? 200 : ms);
const fail = (status: number, message: string): never => {
  throw new ApiError(status, message);
};
const newId = () => `demo-${Math.random().toString(36).slice(2, 10)}`;

// Families ---------------------------------------------------------------------

function generationFor(id: string) {
  return load().generations.find((g) => g.id === id && g.status === 'done');
}

/** A role from the library, or a scenario "built" in the demo from the closest library role. */
function summaryById(id: string): RoleFamilySummary {
  const library = LIBRARY.find((f) => f.id === id);
  if (library) return library;
  const generation = generationFor(id);
  if (!generation) return fail(404, 'Role family not found');
  const { catalog: _catalog, ...base } = LIBRARY.find((f) => f.id === generation.baseFamilyId)!;
  return {
    ...base,
    id: generation.id,
    name: generation.name ?? generation.roleTitle,
    roles: [generation.roleTitle],
    generated: true,
    fixedCurrency: generation.currency,
  };
}

/** The role as set up for one assessment: only the activities the recruiter picked. */
function summaryFor(assessmentId: string): RoleFamilySummary {
  const a = load().assessments[assessmentId];
  const family = summaryById(a.summary.roleFamilyId);
  if (!a.stageIds) return family;
  const ids = new Set(a.stageIds);
  const stages = family.stages.filter((s) => ids.has(s.id));
  const totalMinutes = Math.round(stages.reduce((sum, s) => sum + s.timeLimitSec, 0) / 60);
  return { ...family, stages, totalMinutes };
}

async function preview(id: string, currency: Currency): Promise<RoleFamilyPreview> {
  const family = summaryById(id);
  const baseId = generationFor(id)?.baseFamilyId ?? id;
  const file = PREVIEWS[`./content/previews/${baseId}.json`] ?? fail(404, 'Role family not found');
  const p = (await file()).default[family.fixedCurrency ?? currency];
  return family.generated ? { ...p, family } : p;
}

/** The ready-made role closest to what someone typed, for the demo's "built from your job description". */
function closestFamily(text: string): RoleFamilySummary {
  const words = text.toLowerCase();
  let best = LIBRARY[0];
  let bestScore = -1;
  for (const family of LIBRARY) {
    const terms = [family.name, ...family.roles, ...(family.catalog?.keywords ?? [])].map((t) => t.toLowerCase());
    const score = terms.reduce((sum, term) => sum + (words.includes(term) ? term.length : 0), 0);
    if (score > bestScore) {
      best = family;
      bestScore = score;
    }
  }
  return best;
}

// Assessments -------------------------------------------------------------------

function summaryOf(id: string): AssessmentSummary {
  const s = load();
  const list = s.candidates[id] ?? [];
  const counts = { invited: 0, in_progress: 0, submitted: 0, reviewed: 0, decided: 0 };
  for (const c of list) counts[c.status] += 1;
  return { ...s.assessments[id].summary, candidateCount: list.length, counts };
}

function emptyFunnel(id: string): AssessmentFunnel {
  return {
    invited: load().candidates[id]?.length ?? 0,
    started: 0,
    finished: 0,
    stalledBeforeFirst: 0,
    stalledAfterHours: 0,
    stages: [],
  };
}

function listItem(candidateId: string): { item: CandidateListItem; assessmentId: string } {
  for (const [assessmentId, list] of Object.entries(load().candidates)) {
    const item = list.find((c) => c.id === candidateId);
    if (item) return { item, assessmentId };
  }
  return fail(404, 'Candidate not found');
}

// Candidate reports ---------------------------------------------------------------

/** A report for someone invited in the demo: no answers yet, just the scenario. */
async function inviteReport(candidateId: string): Promise<CandidateReport> {
  const { item, assessmentId } = listItem(candidateId);
  const a = load().assessments[assessmentId].summary;
  const family = summaryFor(assessmentId);
  const sample = await preview(a.roleFamilyId, a.currency);
  const stages: ReportStage[] = family.stages.map((stage, index) => {
    const content = sample.stages.find((s) => s.id === stage.id);
    return {
      id: stage.id,
      index,
      kind: stage.kind,
      title: stage.title,
      scored: stage.scored,
      thinkAloud: stage.thinkAloud,
      timeLimitSec: Math.round(stage.timeLimitSec * item.timeMultiplier),
      shown: null,
      reviewerGuide: content?.variants[0].reviewerGuide ?? [],
      rubric: content?.rubric ?? [],
      dependsOn: stage.dependsOn,
      response: null,
    };
  });
  return {
    candidate: {
      id: item.id,
      name: item.name,
      email: item.email,
      token: item.token,
      idName: null,
      status: item.status,
      timeMultiplier: item.timeMultiplier,
      createdAt: item.createdAt,
      startedAt: null,
      submittedAt: null,
      decision: null,
    },
    assessment: { id: a.id, title: a.title, currency: a.currency },
    family: { id: family.id, name: family.name, generated: Boolean(family.generated) },
    brief: sample.brief,
    stages,
    aiReview: null,
    overrides: [],
    adjusted: null,
    // The call script is written once they submit.
    verification: { script: { opening: [], identity: [], probes: [], closing: [] }, record: null },
    starred: item.starred,
    notes: [],
    benchmark: null,
    siblings: { index: null, total: 0, prev: null, next: null },
    integrity: {
      verdict: 'clean',
      headline: 'Nothing to check until they finish.',
      items: [],
      aiChecked: false,
      checkedAt: null,
    },
    interviewKit: null,
    decisionEmail: null,
  };
}

async function report(candidateId: string): Promise<CandidateReport> {
  return load().reports[candidateId] ?? inviteReport(candidateId);
}

/** Keeps the assessment's candidate list in step with a changed report. */
function syncList(r: CandidateReport) {
  const { item } = listItem(r.candidate.id);
  item.status = r.candidate.status;
  item.decision = r.candidate.decision;
  item.starred = r.starred;
  item.adjustedScore = r.adjusted?.overall ?? null;
}

function stored(candidateId: string): CandidateReport {
  const s = load();
  const r = s.reports[candidateId];
  if (!r) return fail(409, 'The candidate has not finished yet');
  return r;
}

// Candidate demo ---------------------------------------------------------------------

/** Lets someone take the candidate demo again from the start. */
export function restartCandidateDemo() {
  load().candidateDemo = { status: 'invited', responses: [] };
  save();
}

/** A point in the candidate walkthrough: before starting, the brief, one question (by index) or the end. */
export type CandidateFrame = 'intro' | 'brief' | number | 'done';

/**
 * Puts the candidate demo at one screen of the walkthrough: earlier questions
 * answered (the decision with its first option), no timer pressure.
 */
export function showCandidateFrame(frame: CandidateFrame) {
  const demo = load().candidateDemo;
  if (frame === 'intro' || frame === 'done') {
    demo.status = frame === 'intro' ? 'invited' : 'submitted';
    demo.responses = [];
  } else {
    demo.status = 'in_progress';
    const upTo = frame === 'brief' ? 0 : frame + 1;
    const choices: Record<string, string> = {};
    demo.responses = CANDIDATE.stages.slice(0, upTo).map((stage, index) => {
      const view = stage.views[choiceKey(choices)] ?? stage.views[''];
      const choiceId = view.choices?.[0]?.id ?? null;
      if (choiceId) choices[stage.id] = choiceId;
      const open = index === upTo - 1;
      return {
        stageId: stage.id,
        view,
        // A day away: the walkthrough never runs out of time.
        deadlineAt: Date.now() + (open ? 24 * 60 * 60 * 1000 : -SUBMIT_GRACE_MS * 2),
        draft: null,
        closed: !open,
        choiceId: open ? null : choiceId,
      };
    });
  }
  save();
}

function candidatePhase(): CandidatePhaseView {
  const demo = load().candidateDemo;
  if (demo.status === 'invited') return { phase: 'intro' };
  if (demo.status === 'submitted') return { phase: 'done' };
  const now = Date.now();
  for (const [index, stage] of CANDIDATE.stages.entries()) {
    const response = demo.responses.find((r) => r.stageId === stage.id);
    if (!response) {
      return {
        phase: 'ready',
        next: { index, kind: stage.kind, timeLimitSec: stage.timeLimitSec, thinkAloud: stage.thinkAloud },
      };
    }
    if (response.closed) continue;
    if (now > response.deadlineAt + SUBMIT_GRACE_MS) {
      response.closed = true;
      continue;
    }
    return {
      phase: 'stage',
      stage: response.view,
      deadlineAt: response.deadlineAt,
      draft: response.draft,
      audio: null,
    };
  }
  demo.status = 'submitted';
  return { phase: 'done' };
}

function candidateSession(): CandidateSession {
  const phase = candidatePhase();
  save();
  const minutes = CANDIDATE.stages.map((stage) => stage.timeLimitSec / 60);
  return {
    serverNow: Date.now(),
    candidate: {
      name: 'Riya Sharma',
      email: 'riya@example.com',
      linkedToAccount: false,
      status: load().candidateDemo.status,
      timeMultiplier: CANDIDATE.timeMultiplier,
    },
    assessment: {
      title: 'Growth Marketing Manager',
      orgName: 'Demo Co',
      roleFamilyName: CANDIDATE.familyName,
      uniqueNumbers: true,
      totalMinutes: Math.round(minutes.reduce((a, b) => a + b, 0)),
      outline: CANDIDATE.stages.map((stage, i) => ({
        kind: stage.kind,
        minutes: Math.round(minutes[i] * 10) / 10,
        thinkAloud: stage.thinkAloud,
      })),
    },
    brief: phase.phase === 'intro' ? null : CANDIDATE.brief,
    state: phase,
  };
}

function candidateCall(method: string, rest: string[], body: Record<string, unknown>) {
  const demo = load().candidateDemo;
  const [action, stageId, sub] = rest;
  if (method === 'GET' && !action) return candidateSession();
  if (method === 'POST' && action === 'start') {
    if (body.consent !== true) fail(400, 'Please confirm you have read how this assessment works');
    if (demo.status === 'invited') demo.status = 'in_progress';
    return candidateSession();
  }
  if (method === 'POST' && action === 'next') {
    const phase = candidatePhase();
    const index = Number(body.index);
    if (phase.phase === 'stage' && phase.stage.index === index) return candidateSession();
    if (phase.phase !== 'ready' || phase.next.index !== index) fail(409, 'Questions have to be answered in order');
    const stage = CANDIDATE.stages[index];
    const choices = Object.fromEntries(demo.responses.map((r) => [r.stageId, r.choiceId]));
    const view = stage.views[choiceKey(choices)] ?? stage.views[''];
    demo.responses.push({
      stageId: stage.id,
      view,
      deadlineAt: Date.now() + view.timeLimitSec * 1000,
      draft: null,
      closed: false,
      choiceId: null,
    });
    return candidateSession();
  }
  if (action === 'stages' && stageId) {
    const response = demo.responses.find((r) => r.stageId === stageId);
    // Recordings stay in the browser in the demo.
    if (sub === 'stream' || sub === 'audio') return { ok: true, received: 1 };
    if (!response || response.closed) {
      return fail(409, 'Time ran out for this question. Your last autosaved draft was kept.');
    }
    if (method === 'PUT' && sub === 'draft') {
      response.draft = body as CandidateDraft;
      save();
      return { ok: true, serverNow: Date.now() };
    }
    if (method === 'POST' && sub === 'submit') {
      const stage = CANDIDATE.stages.find((s) => s.id === stageId)!;
      const text = typeof body.text === 'string' ? body.text.trim() : '';
      if (body.timedOut !== true) {
        if (stage.kind === 'decision' && !body.choiceId) fail(400, 'Choose an option before submitting');
        if (stage.kind === 'ai_allowed' && !text) fail(400, 'Paste your final answer before submitting');
        if (!text && !stage.thinkAloud) fail(400, 'Type an answer before submitting');
      }
      response.closed = true;
      response.choiceId = typeof body.choiceId === 'string' ? body.choiceId : null;
      return candidateSession();
    }
  }
  return fail(404, 'In the demo, only the demo assessment link works. Try the candidate demo from the home page.');
}

// Activity log ------------------------------------------------------------------------

/** A plausible activity log, built from the sample workspace. */
function demoActivity(s: State): AuditEvent[] {
  const events: AuditEvent[] = [];
  const add = (createdAt: number, action: string, target: string | null = null, detail: string | null = null) =>
    events.push({ id: newId(), actor: s.me.email, action, target, detail, createdAt });
  for (const a of Object.values(s.assessments)) {
    add(a.summary.createdAt, 'created an assessment', a.summary.title);
    for (const c of s.candidates[a.summary.id] ?? [])
      add(c.createdAt + 60_000, 'invited a candidate', c.name, a.summary.title);
  }
  for (const r of Object.values(s.reports)) {
    if (r.candidate.decision) add(Date.now() - 5 * 60_000, `decided: ${r.candidate.decision}`, r.candidate.name);
  }
  add(Date.now() - 30 * 60_000, 'signed in', null, 'password');
  return events.sort((x, y) => y.createdAt - x.createdAt);
}

// Routing ------------------------------------------------------------------------------

export async function handle(method: string, url: string, body: unknown = {}): Promise<unknown> {
  const s = load();
  const { pathname, searchParams } = new URL(url, 'http://demo');
  const parts = pathname.replace(/^\/api\//, '').split('/');
  const b = (body ?? {}) as Record<string, unknown>;
  await wait(120);

  // Auth
  if (pathname === '/api/auth/me') return { user: s.me };
  if (pathname === '/api/candidate/auth/me') return { candidate: null };
  if (pathname === '/api/auth/logout' || pathname === '/api/candidate/auth/logout') {
    exitDemo();
    return { ok: true };
  }
  if (pathname === '/api/candidate/assessments') return { assessments: [] };
  if (pathname === '/api/auth/security') return { twoFactor: false, recoveryCodesLeft: 0 };
  if (pathname.startsWith('/api/auth/2fa') || pathname.startsWith('/api/auth/sessions')) {
    return fail(409, 'In the demo, sign-in settings can’t be changed. Start free to set up two-factor sign-in.');
  }
  if (pathname === '/api/audit') return { events: demoActivity(s) };

  // Candidate demo
  if (parts[0] === 'c') {
    if (parts[1] !== DEMO_TOKEN) {
      return fail(404, 'In the demo, invite links don\'t open. Try "Try as a candidate" on the home page.');
    }
    const result = candidateCall(method, parts.slice(2), b);
    save();
    return result;
  }

  const result = await recruiterCall(method, parts, b, searchParams);
  save();
  return result;
}

async function recruiterCall(
  method: string,
  parts: string[],
  b: Record<string, unknown>,
  query: URLSearchParams,
): Promise<unknown> {
  const s = load();
  const [area, id, sub, a, c] = parts;
  const now = Date.now();

  if (area === 'plan' && !id) return s.plan;
  if (area === 'plan' && id === 'upgrade-request' && method === 'POST') {
    s.plan.upgradeRequest = { plan: String(b.plan), createdAt: now };
    return s.plan;
  }

  if (area === 'team') {
    if (method === 'POST') {
      s.team.push({
        id: newId(),
        name: String(b.name ?? ''),
        email: String(b.email ?? ''),
        role: 'manager',
        createdAt: now,
      });
      return { id: s.team.at(-1)!.id };
    }
    return { team: s.team };
  }

  if (area === 'role-families') {
    if (!id) {
      const generated = s.generations.filter((g) => g.status === 'done').map((g) => summaryById(g.id));
      return { families: [...generated, ...LIBRARY] };
    }
    // One sample version per role in the demo, whatever seed is asked for.
    if (sub === 'preview') return preview(id, query.get('currency') === 'USD' ? 'USD' : 'INR');
  }

  if (area === 'generations') {
    // The demo doesn't run AI: after a short wait, it uses the closest ready-made scenario.
    const view = (g: DemoGeneration): GenerationView => {
      if (g.status === 'running' && now - g.createdAt > 8000) {
        g.status = 'done';
        g.updatedAt = now;
        g.name = `${g.roleTitle} (demo)`;
      }
      const { baseFamilyId: _base, ...rest } = g;
      return rest;
    };
    if (!id && method === 'GET') return { generations: s.generations.map(view) };
    if (!id && method === 'POST') {
      const roleTitle = String(b.roleTitle ?? '').trim() || 'New role';
      const description = String(b.description ?? '');
      const generation: DemoGeneration = {
        id: newId(),
        roleTitle,
        description,
        currency: b.currency === 'USD' ? 'USD' : 'INR',
        status: 'running',
        error: null,
        name: null,
        source: b.source === 'jd' ? 'jd' : 'description',
        createdAt: now,
        updatedAt: now,
        assessmentCount: 0,
        baseFamilyId: closestFamily(`${roleTitle} ${description}`).id,
      };
      s.generations.unshift(generation);
      return { id: generation.id };
    }
    const generation = s.generations.find((g) => g.id === id) ?? fail(404, 'Scenario not found');
    if (method === 'DELETE') {
      s.generations = s.generations.filter((g) => g.id !== id);
      return { ok: true };
    }
    return view(generation);
  }

  if (area === 'assessments') {
    if (!id && method === 'GET') {
      const ids = Object.keys(s.assessments).sort(
        (x, y) => s.assessments[y].summary.createdAt - s.assessments[x].summary.createdAt,
      );
      return { assessments: ids.map(summaryOf) };
    }
    if (!id && method === 'POST') {
      const family = summaryById(String(b.roleFamilyId));
      const assessmentId = newId();
      s.assessments[assessmentId] = {
        summary: {
          id: assessmentId,
          title: String(b.title ?? family.name),
          roleFamilyId: family.id,
          roleFamilyName: family.name,
          currency: family.fixedCurrency ?? (b.currency === 'USD' ? 'USD' : 'INR'),
          createdAt: now,
        },
        stageIds: Array.isArray(b.stageIds) ? (b.stageIds as string[]) : null,
      };
      s.candidates[assessmentId] = [];
      const generation = s.generations.find((g) => g.id === family.id);
      if (generation) generation.assessmentCount += 1;
      return { id: assessmentId };
    }
    if (!s.assessments[id]) return fail(404, 'Assessment not found');
    if (!sub) {
      return {
        assessment: summaryOf(id),
        family: summaryFor(id),
        candidates: s.candidates[id],
      } satisfies AssessmentDetail;
    }
    if (sub === 'funnel') return s.funnels[id] ?? emptyFunnel(id);
    if (sub === 'candidates') {
      const people: { name: unknown; email: unknown }[] = a === 'bulk' ? ((b.people as never[]) ?? []) : [b as never];
      const multiplier = Number(b.timeMultiplier ?? 1) || 1;
      const existing = new Set(s.candidates[id].map((x) => x.email.toLowerCase()));
      const created: CandidateListItem[] = [];
      const skipped: { name: string; email: string; reason: string }[] = [];
      for (const person of people) {
        const name = String(person.name ?? '').trim();
        const email = String(person.email ?? '').trim();
        if (!name) skipped.push({ name, email, reason: 'Name is required' });
        else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
          skipped.push({ name, email, reason: 'Email must be a valid email address' });
        else if (existing.has(email.toLowerCase()))
          skipped.push({ name, email, reason: 'Already invited to this assessment' });
        else {
          existing.add(email.toLowerCase());
          const candidateId = newId();
          created.push({
            id: candidateId,
            name,
            email,
            token: `${candidateId}-link`,
            status: 'invited',
            timeMultiplier: multiplier,
            createdAt: now,
            startedAt: null,
            submittedAt: null,
            aiScore: null,
            aiStatus: null,
            aiRecommendation: null,
            adjustedScore: null,
            notableSignals: 0,
            verification: null,
            decision: null,
            starred: false,
          });
        }
      }
      s.candidates[id] = [...[...created].reverse(), ...s.candidates[id]];
      if (a === 'bulk') return { created, skipped };
      if (skipped.length) return fail(400, skipped[0].reason);
      return { candidate: created[0] };
    }
  }

  if (area === 'candidates' && id) {
    if (!sub && method === 'GET') return report(id);
    if (sub === 'star') {
      const { item } = listItem(id);
      item.starred = Boolean(b.starred);
      if (s.reports[id]) s.reports[id].starred = item.starred;
      return { starred: item.starred };
    }
    if (sub === 'decision') {
      const r = stored(id);
      const decision = (b.decision ?? null) as Decision | null;
      r.candidate.decision = decision;
      r.candidate.status = decision ? 'decided' : r.aiReview?.status === 'done' ? 'reviewed' : 'submitted';
      r.decisionEmail = null;
      syncList(r);
      return r;
    }
    if (sub === 'notes') {
      const r = stored(id);
      if (method === 'POST') {
        const text = String(b.body ?? '').trim();
        if (!text) fail(400, 'Note is required');
        r.notes.push({
          id: newId(),
          userName: s.me.name,
          body: text,
          lean: (b.lean ?? null) as Decision | null,
          createdAt: now,
          mine: true,
        });
      } else r.notes = r.notes.filter((n) => n.id !== a);
      return r;
    }
    if (sub === 'overrides') {
      const r = stored(id);
      if (method === 'PUT') {
        const stageId = String(b.stageId);
        const criterionId = String(b.criterionId);
        const aiScore = r.aiReview?.result?.stages.find((x) => x.stageId === stageId)?.criteria[criterionId]?.score;
        if (aiScore === undefined) fail(409, 'There is no AI score to disagree with yet');
        const override: ScoreOverride = {
          stageId,
          criterionId,
          aiScore: aiScore!,
          score: Number(b.score),
          note: String(b.note ?? ''),
          userName: s.me.name,
          updatedAt: now,
        };
        r.overrides = [
          ...r.overrides.filter((o) => !(o.stageId === stageId && o.criterionId === criterionId)),
          override,
        ];
      } else {
        r.overrides = r.overrides.filter((o) => !(o.stageId === a && o.criterionId === c));
      }
      r.adjusted = adjustedScores({ stages: r.stages }, r.aiReview?.result ?? null, r.overrides);
      syncList(r);
      return r;
    }
    if (sub === 'verification') {
      const r = stored(id);
      r.verification.record = {
        identity: (b.identity ?? null) as never,
        consistency: (b.consistency ?? null) as never,
        notes: String(b.notes ?? ''),
        interviewerName: s.me.name,
        updatedAt: now,
      };
      return r;
    }
    if (sub === 'ai-review')
      return fail(409, "In the demo, AI reviews are written in advance, so they can't be re-run.");
    if (sub === 'integrity-check') {
      const r = stored(id);
      if (!r.integrity.aiChecked)
        fail(409, 'In the demo, integrity checks are written in advance for the finished candidates.');
      await writing(900);
      return r;
    }
    if (sub === 'interview-kit') {
      const r = stored(id);
      if (!r.interviewKit) fail(409, 'In the demo, interview kits are written in advance for the finished candidates.');
      await writing(1500);
      r.interviewKit = { ...r.interviewKit!, createdAt: now };
      return r;
    }
    if (sub === 'decision-email') {
      const r = stored(id);
      const decision = r.candidate.decision ?? fail(409, 'Make a decision first');
      await writing(1000);
      const written = s.emails[id]?.[decision];
      r.decisionEmail = written
        ? { ...written, createdAt: now }
        : {
            decision,
            ...templateEmail(decision, {
              candidateName: r.candidate.name,
              title: r.assessment.title,
              orgName: s.me.orgName,
              senderName: s.me.name,
            }),
            ai: false,
            createdAt: now,
          };
      return r;
    }
  }

  return fail(404, "This isn't available in the demo.");
}
